### ISSUE TITLE
Could this be simulated in cooja?

### ISSUE THREAD

**Issue by ShaoZongxu** [skimskimskim/ALICE#1]

**Comment by skimskimskim** [comment]
Hi, ShaoZongxu !
Thanks for your interest on ALICE.

I remember that the available motes in Cooja have small memory size.
For this reason, we have only tested ALICE on real devices (openmote-cc2538 and iotlab-M3).

Cheers,
Seohyang.

**Comment by ShaoZongxu** [comment]
Thanks for your help！




------------------ 原始邮件 ------------------
发件人: "skimskimskim"<notifications@github.com>; 
发送时间: 2019年5月9日(星期四) 上午10:25
收件人: "skimskimskim/ALICE"<ALICE@noreply.github.com>; 
抄送: "1563816786"<1563816786@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [skimskimskim/ALICE] Could this be simulated in cooja? (#1)




Hi, ShaoZongxu !
 Thanks for your interest on ALICE.
 
I remember that the available motes in Cooja have small memory size.
 For this reason, we have only tested ALICE on real devices (openmote-cc2538 and iotlab-M3).
 
Cheers,
 Seohyang.

**Comment by ShaoZongxu** [comment]
Sorry to bother you again,do you have source code or any implementation of e-TSCH-Orch?




------------------ 原始邮件 ------------------
发件人: "skimskimskim"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 上午10:25
收件人: "skimskimskim/ALICE"<ALICE@noreply.github.com>;
抄送: "1563816786"<1563816786@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [skimskimskim/ALICE] Could this be simulated in cooja? (#1)




Hi, ShaoZongxu !
 Thanks for your interest on ALICE.
 
I remember that the available motes in Cooja have small memory size.
 For this reason, we have only tested ALICE on real devices (openmote-cc2538 and iotlab-M3).
 
Cheers,
 Seohyang.

**Comment by skimskimskim** [comment]
Hi, ShaoZongxu ! We do not have any source code or implementation of e-TSCH-Orch.

**Comment by skimskimskim** [comment]
Hi, ShaoZongxu ! 

I implemented AILCE on Contiki-NG.
The source code is available at : https://github.com/skimskimskim/contiki-ng

Moreover, you can run ALICE even in Cooja simulator.
Example source code is also provided.
I hope you enjoy my implementation !

Cheers,
Seohyang.
