### ISSUE TITLE
CC2650 sram overfolw！how to solve this problem

### ISSUE THREAD

**Issue by ShaoZongxu** [skimskimskim/ALICE#2]
compile example this code offered

**Comment by skimskimskim** [comment]
Hi, ShaoZongxu !
Thank you for your interest.

ALICE is based on RPL storing mode requiring large memory size compared to RPL non-storing mode.
Especially when we use large routing table size and large neighbor table size, we need more memory.

We evaluated ALICE on Openmote-cc2538 and IoT-LAB M3  nodes with the provided source code.
These devices provide enough memory to run ALICE.

In the provided example code (in the example directory), we set the maximum node number as 70 (#define MAX_NODE_NUM 70). It is also used for both routing table and neighbor table size. You can adjust this value based on your network configuration.

Thank you !

Cheers,
Seohyang.
